apiVersion: v1
kind: ConfigMap
metadata: 
 name: myconfig
data: 
  app: devop
  trainer: raghuramulu
---
apiVersion: v1
kind: Pod
metadata: 
 name: pod-config
 labels: 
   app: mydevop
   tier: web
spec:
 containers:
  - name: pod-with
    image: nginx
    envFrom:
     - configMapref:
         name: myconfig
    ports:
      - containerPort: 80

