apiVersion: v1
kind: Pod
metadata: 
  name: env-pod
  labels:
    app: devops
    training: started
spec:
  containers:
    - name: env-pod
      image: nginx
      env:
       - name: demo-greeting
         value: "hai"
