apiVersion: v1
kind: Pod
metadata: 
 name: pod-cluster
 labels: 
  app: nginx
  demo: service
spec:
 containers: 
  - name: myservice
    image: nginx
    ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
 name: pod-cluster
spec:
 selector: 
  app: nginx
  demo: service
 ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
